kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-configuration
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: nginx
    k8s.scw.cloud/object: ConfigMap
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-tcp-services
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: nginx
    k8s.scw.cloud/object: ConfigMap
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-udp-services
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    k8s.scw.cloud/system: ingress
    k8s.scw.cloud/ingress: nginx
    k8s.scw.cloud/object: ConfigMap
